### ISSUE TITLE
Failing test on master

### ISSUE THREAD

**Issue by MerzDaniel** [actano/rplan-express-middleware#1]
The following test is currently failing: 

https://github.com/actano/rplan-express-middleware/blob/92719b66f41a92bd72c63c00eecf72a54e97c020/test/logging-handler.test.js#L54

**Comment by pithu** [comment]
works for me, locally and on travis see https://travis-ci.org/actano/rplan-express-middleware

**Comment by MerzDaniel** [comment]
Found the problem:
You're using Node 8 and the test is running when using that version

I thought we switched to Node 10 now? End of life for Node 8 is already this december.

**Comment by pithu** [comment]
I am using node 10 locally, i just update travis config to use node 10, build succeed.

I cant reproduce the error.

**Comment by pithu** [comment]
Ah might be an os related issue with carriage return. see  file ./test/helper/capture-stdout.js

**Comment by rendner** [comment]
Closed because the problem is no longer present.
